#!/bin/sh -e

libdir="/mnt/c/Users/user/Desktop/Joel/Spirent_Internship/nghttp2-1.41.0/lib"
if [ -d "$libdir/.libs" ]; then
    libdir="$libdir/.libs"
fi

export CGO_CFLAGS="-I/mnt/c/Users/user/Desktop/Joel/Spirent_Internship/nghttp2-1.41.0/lib/includes -I/mnt/c/Users/user/Desktop/Joel/Spirent_Internship/nghttp2-1.41.0/lib/includes"
export CGO_LDFLAGS="-L$libdir"
export LD_LIBRARY_PATH="$libdir"
export GODEBUG=cgocheck=0
"$@"
